# Generated by Django 3.2 on 2021-11-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('size', models.FloatField()),
                ('purchase_price', models.IntegerField()),
                ('estimated_profit', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('project_background', models.TextField()),
            ],
        ),
    ]
