# Generated by Django 3.2 on 2021-11-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='applied_date',
            field=models.DateField(auto_now=True),
        ),
    ]
