# Generated by Django 3.2 on 2021-11-25 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='comment',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='item.itemcheck'),
        ),
    ]
