# Generated by Django 3.2 on 2021-11-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20211126_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcheck',
            name='status',
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.IntegerField(choices=[(0, '申請中'), (1, '承認'), (2, '却下')], default=0),
        ),
    ]
