# Generated by Django 3.2 on 2021-11-28 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_remove_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.IntegerField(choices=[(0, '申請中'), (1, '承認'), (2, '却下')], default=0),
        ),
    ]
